CREATE TABLE scores(
    id NUMBER(1) PRIMARY KEY,
    score NUMBER(3,2)
);

INSERT INTO scores VALUES(1,3.50);
INSERT INTO scores VALUES(2,4.00);
INSERT INTO scores VALUES(3,3.65);
INSERT INTO scores VALUES(4,3.85);
INSERT INTO scores VALUES(5,4.00);
INSERT INTO scores VALUES(6,3.65);

SELECT ROUND(score,2),DENSE_RANK() OVER (ORDER BY score DESC) AS rank 
FROM scores;
